services:
  - type: web
    name: hotel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          name: mysql-db
          type: pserv
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          name: mysql-db
          type: pserv
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: com.mysql.cj.jdbc.Driver
      - key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE_JDBCTEMPLATE
        value: DEBUG

  - type: pserv
    name: mysql-db
    env: docker
    plan: free
    dockerfilePath: "" # leave blank since using built-in MySQL
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_DATABASE
        value: hotel
      - key: MYSQL_USER
        generateValue: true
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
