services:
  # Spring Boot API Service
  - type: web
    name: MajorProject
    env: docker
    repo: https://github.com/umesh1522/Restaurant-Website-Using-SpringBoot.git
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    # Automatically builds and deploys on push to main branch
    autoDeploy: true
    # Environment variables
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: MajorProject
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.MySQL8Dialect
      # Upload settings
      - key: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
        value: 10MB
      - key: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
        value: 10MB
      # Static resources
      - key: SPRING_WEB_RESOURCES_STATIC_LOCATIONS
        value: "classpath:/static/,file:uploads/"
      # Database connection
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-db:3306/hotel
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: com.mysql.cj.jdbc.Driver
      # Logging settings
      - key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE_JDBCTEMPLATE
        value: DEBUG
  
  # MySQL Database Service
  - type: pserv
    name: mysql-db
    env: docker
    plan: standard
    repo: https://github.com/umesh1522/Restaurant-Website-Using-SpringBoot.git
    buildCommand: echo "Building MySQL service"
    startCommand: |
      docker run --name mysql-db \
        -e MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}" \
        -e MYSQL_DATABASE=hotel \
        -v ${RENDER_MOUNT_PATH}:/var/lib/mysql \
        -p 3306:3306 \
        mysql:8
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
